language: node_js
node_js:
- '6'
addons:
  apt:
    packages:
    - lftp
branches:
  only:
    - master
env:
  global:
    - secure: v39By88qMnPvcnk3SrqJxbpj6qwokqyF63bpcsHJL2qhUgbKuXq7zgkRf/BUwBi6wTi2n1f3ZVdvjzSZatAU0dp1nDPvwtCytJy4lKrKUwixbxwWKT5eYhScGpxu+EJzxDu1s8Zy1OaFxs8Mbe4yZ+GNGbjwIBtSr+H8BhYv/k9MOdoYb6LjXETk7XAlI1cUBcG9aHAjG1F/HBuLwWTMHLG7vrFI6QdE7RDpEdoVaxm2Eo+fVkYKMnTzTVgZIs53hH3ALOcbBc+Vqyh+pPqrh9s3iC/YzNxyhouln11a8+GSw4wlfUBaDfckXFV9fB6D996L9YeVc1e2wfqQHNjDvh7huoXzPtxDKoItGyJw+ACYFPQKSAw+jelXVtlQnBmJoQv0g1IaM9OwYHDHEsPOISbBCbyODb0mgGIVtH9UTrjOVXiCkVVVngJKFZN98LVC8GoUsR7MAouJKJfSeoCC1QwIz6/qpWh0wPvglAHehUy5qsD/y0D1UD3ycc45D8jWarQAGQD4Aatc6fmHGCo2GDsXizdfQrjy5acBvRyUrTVcHm4TVYKjuULDh4yyPwrMpRteP/5I1P8ix/flQT00aiKSUKxFvmXK37UeQpZTUbTU9JH27dc4Dvlnmzaf5sAonAHaudTDSC65sv/dVPHjoEC84m4vxtpilrL+qrAtg/Y=
    - secure: Zd/wYGozdZHtN0XZS7OF+MZlyCZ7sb1s9RUYpyNAaw4QedXiyIZxmcPdptlUfhy1S7fgTZeYe1IDpjRxNhGEVy/8Thb0+rq+0BeksEmVr6RzavTQ0SIQYiV+nlb93tlEk0VYONz2Fst5yAcLW9X9Yg9JTFKrIYzEvdIrXOqkQwufjHQ4Wn0wSgYYLWUfhvX60hlaowbVH0csFd8LX8b/Wo+JOOnxBvpnam2WwM6jXNbx8x/o782GTCu/i3lh0W0zfEI6qy+s7GF3LuBpLCM7xLLHB6f8obYBqOEjCZlADm66oMBQRIjOGtdKlV5LjAWk/gidtviiAZ3C6N9b6HfNOiLpBJsAjLJYoY6MaCRNE+uuKt8LM0e5cC05iHdgBAFJL5XlRtrCGjjSjvhMS1qXzP1AmEgrvYC99CL5QhOO3BJsq+BC/OzL0JgRLXMjd+CHe1eOB1p3V97kSWJtG2QUHljIosTFi7rwm9j9BrGFIsgEPKxpl8hXL9aAURww5ZqFPz9zioVjgOJ6m8h3kMajGYut42IVaV1W2qvagATU+JAugVwrfLPoWEqYxsmnSKODioE2yFyiBy3ZDDagrlfv7ZHQLDH6eDndFm2TZSO2yXIFw/m4Z2PbJCiDzUFfGDczj6LCAjcP1HvyuTRwL7Xz9Z8KVtdqRFtoX5p6AzXOUGU=
    - secure: lOXxyTwsbCsLP0V9xAIWGoKtPgrDSHyYancHqNuJtgltL3RGR+gPV2E5WSS6C5Zu4B9bicEP3IBw02gQJf2s/WKMOyIxKXilRA0ULP4wWRzShA/LryMWzREc0n+qF+/934StCeltwIYFcjyTeT9EWLZbmOP/DpiGKkEiRY38uqwOnmw5NB2w/qjDXZ7tYayR1KjUhOWh+AYSJLw5J72defAb/WAhmCJ/YrHezK2tH5bQSmqU8qOfngjxW9YK+Y5mHHeMbgDx5xGR7yB7YqRznxMye+ofek8i0RY7FMllp2brF/CHO6GqgCd33FjWLetu8JzKC+Mqzddhui2DzClwopO5AP+aX3nYepDiUuRE7bEhRm6ofDoW5bZvXazOQlY2+7ewgtQqoepjfxFtEDz2AS1Q9OWocA9HpO21qop62v2pkYt3qAJTs0q1/bFvJlCtnRaDIYWL+qcH0QUQzD09PjYZKsvpdmD4cE4FUvE3koeq1KVaIewSSfGayhWoCgqEnCjzsrUglph+DJ6X1o5ITx4j+R4h1EOXfIwFnZ5kfIpNvwy7RvhnVKni4Ty4wS2apM+9ImWZloc0VjP65K12gYvpvADWmOA79jfoy52dIUhg6XpTC+MTqf9Eq9LIzSHr4vZSjnsdseGAuwulHw41yrUWxBf5GEWxXvkogKAk2+s=
after_success:
- echo "deploying..."
- lftp -c "open -u $USER,$PASSWORD $HOST; mirror -R $TRAVIS_BUILD_DIR/api ~/backend/api"
- lftp -c "open -u $USER,$PASSWORD $HOST; put -O ~/backend $TRAVIS_BUILD_DIR/package.json"
- lftp -c "open -u $USER,$PASSWORD $HOST; put -O ~/backend $TRAVIS_BUILD_DIR/app.js"
- echo "deploy done"
